apiVersion: v1
kind: ConfigMap
metadata:
  name: swiftpay-config
  namespace: swiftpay
data:
  KAFKA_BOOTSTRAP: "kafka:9092"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
